### ISSUE TITLE
Base64 encoding fix

### ISSUE THREAD

**Issue by softexpert** [karlseguin/jsonwriter#5]
In case someone uses a io.Reader to supply data in a Value, the base64 encoder might exhibit a bug.
The fix is to add an explicit **Close** to the base64 encoder:

```go
	case io.Reader:
		w.W.Write(quote)
		b64W := base64.NewEncoder(base64.RawStdEncoding.WithPadding('='), w.W)
		io.Copy(b64W, value.(io.Reader))
		b64W.Close()
		w.W.Write(quote)

```

The explanation: not closing the base64 encoder results in truncated content - the last buffer contents that have not been flushed will not be encoded.

I learned this the hard way, while chasing a missing byte ...

**Comment by karlseguin** [comment]
`NewEncoder` *does* return an `io.WriteCloser` and it's generally safe to guess that if something implements `Close()`, you should call it.

**Comment by karlseguin** [comment]
> a bit less, however, about the outcome.

Sorry, it's a library I haven't touched in a while, and I was having a hard time understanding, from your original issue, exactly how it related.

I'll take a closer look tomorrow :)

**Comment by karlseguin** [comment]
I added support for an io.Reader to `Value()` (which is used by `KeyValue`). My go is a little rusty, so if you get the chance to review the code, I'd appreciate it.

**Comment by karlseguin** [comment]
I added a `KeyReader`, and added the defers to the original version to ensure Close is called.

**Comment by softexpert** [comment]
Looks good to me!
Thank you very much!
